# multinomial action selector
action_selector: "multinomial_seq"
epsilon_start: 1.0
epsilon_finish: .05
epsilon_anneal_time: 50000
mask_before_softmax: False
mac: "dfop_mac"
runner: "sequential"

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
c_lr: 0.0005

# use COMA
agent_output_type: "pi_logits"
td_lambda: 0.8
learner: "dfop_learner"

name: "dfop"
buffer_size: 5000

# use QPLEX
mixing_embed_dim: 64
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64

# use QATTEN
n_head: 4  
attend_reg_coef: 0.001  
burn_in_period: 100

# process dependency
dep_n_head: 4
dep_embed_dim: 64
dep_kv_dim: 64
dep_output_dim: 64

